//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ducky.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Socials : global::System.Configuration.ApplicationSettingsBase {
        
        private static Socials defaultInstance = ((Socials)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Socials())));
        
        public static Socials Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("63305")]
        public int TelegramApiID {
            get {
                return ((int)(this["TelegramApiID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("371ba1c190e97d690122fbf99735ef3f")]
        public string TelegramApiHash {
            get {
                return ((string)(this["TelegramApiHash"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong TelegramUserID {
            get {
                return ((ulong)(this["TelegramUserID"]));
            }
            set {
                this["TelegramUserID"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vlf9a4486ky1mxdp7zeiedskxkxh8j")]
        public string TwitchAppClientID {
            get {
                return ((string)(this["TwitchAppClientID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5k791zxugyilu0kecgpvtog2o6lp12")]
        public string TwitchAppClientSecret {
            get {
                return ((string)(this["TwitchAppClientSecret"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchUserAccess_token {
            get {
                return ((string)(this["TwitchUserAccess_token"]));
            }
            set {
                this["TwitchUserAccess_token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchUserRefresh_token {
            get {
                return ((string)(this["TwitchUserRefresh_token"]));
            }
            set {
                this["TwitchUserRefresh_token"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("863198368:AAFxmAOsWDHKOB3aaMHbCXWhjJABe4FG4ps")]
        public string TwitchBotToken {
            get {
                return ((string)(this["TwitchBotToken"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong VkUserId {
            get {
                return ((ulong)(this["VkUserId"]));
            }
            set {
                this["VkUserId"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7189275")]
        public ulong VkAppId {
            get {
                return ((ulong)(this["VkAppId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("188159188")]
        public ulong VkGroupId {
            get {
                return ((ulong)(this["VkGroupId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5afd80161deb929433093eda3dffaf5842fbb12049d14c9e4c1fa937cd94a517760d01b3be2cdd9bb" +
            "8c73")]
        public string VkAccessKey {
            get {
                return ((string)(this["VkAccessKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0SgT1Q6YXZDNLQEgByWg")]
        public string VkSecurityKey {
            get {
                return ((string)(this["VkSecurityKey"]));
            }
        }
    }
}
